name: socialdiary_project
description: A new Flutter project.
publish_to: 'none'  # 공개하지 않도록 설정
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'  # Dart SDK 버전 요구 사항

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6  # iOS 스타일 아이콘을 위한 패키지
  table_calendar: ^3.1.2  # 캘린더 UI를 제공하는 패키지
  provider: ^6.0.2  # 상태 관리 패키지
  shared_preferences: ^2.0.15  # 데이터를 로컬 저장소에 저장하기 위한 패키지
  image_picker: ^1.1.2  # 이미지 및 동영상 선택을 위한 패키지
  geocoding: ^3.0.0  # 좌표를 주소로 변환하거나 주소를 좌표로 변환하는 패키지
  permission_handler: ^11.3.1  # 권한 요청을 처리하는 패키지
  google_maps_flutter: ^2.9.0  # Google Maps 통합을 위한 패키지
  hive: ^2.0.0  # Hive 패키지, 경량 로컬 저장소
  hive_flutter: ^1.1.0  # Hive를 Flutter와 함께 사용하기 위한 패키지
  path_provider: ^2.0.0  # 경로 탐색 패키지 (파일 시스템에 접근)
  geolocator: ^12.0.0  # geolocator 버전을 12.x.x로 낮춤 (firebase_auth와 호환)
  firebase_auth: ^5.2.0  # Firebase 인증을 위한 패키지
  firebase_core: ^3.4.0  # Firebase 핵심 패키지

dev_dependencies:
  hive_generator: ^2.0.1  # Hive 어댑터 생성을 위한 코드 생성기
  build_runner: ^2.4.11  # 코드 생성을 위한 도구
  flutter_test:
    sdk: flutter  # Flutter 테스트 프레임워크
  flutter_lints: ^4.0.0  # 코드 품질 검사 도구

flutter:
  uses-material-design: true  # Flutter 프로젝트에 Material 디자인을 사용
